//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string cardNumber { get; set; }
        public string validDate { get; set; }
        public string cardKey { get; set; }
    }
}
