//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int Id { get; set; }
        public int IdObject { get; set; }
        public string IdsProducts { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public string Card { get; set; }
        public System.DateTime CreationTime { get; set; }
        public byte AcceptStatus { get; set; }
        public byte PaymentStatus { get; set; }
        public byte DeliveryStatus { get; set; }
        public System.DateTime DeliveryTime { get; set; }
    }
}
